source 'https://rubygems.org' do
  gem 'sinatra'
  gem 'activerecord'
  gem 'bcrypt'
  gem 'em-websocket'
  gem 'sqlite3'
  gem 'thin'
  gem 'pry'
  gem 'resque'
  gem 'whenever'
  gem 'nmap-parser'
  gem 'haml'
  gem 'rack'
  gem 'websocket-rack'
  gem 'resque-backtrace', require: false
  gem 'csvreader'
  gem 'grape'
  gem 'sinatra-contrib'
  gem 'mechanize'
  gem 'faye-websocket'
  gem 'wpscan'
  gem 'gastly'
  gem 'pg'
  gem 'ruby-vnc'
  gem 'textacular'
  gem 'erubis'
  gem 'actionview'
  gem 'filelock'
  gem 'addressable'
end
